---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: notify-slack-on-failure
spec:
  description: |-
    Sends an error message to Slack using postMessage API if managed pipelines fail.
    Optionally, it can also send a notification on success.
  params:
    - name: secretName
      description: Name of secret which contains authentication token for app
    - name: secretKeyName
      description: Name of key within secret which contains webhook URL
    - name: release
      description: Namespaced name of release - should be in format "namespace/name"
    - name: notifySuccess
      description: If set to "true", it will also send notification on success
      default: "false"
  volumes:
    - name: slack-token
      secret:
        secretName: $(params.secretName)
        optional: true
  steps:
    - name: notify-failure
      image: quay.io/konflux-ci/release-service-utils:e633d51cd41d73e4b3310face21bb980af7a662f
      volumeMounts:
        - name: slack-token
          mountPath: "/etc/secrets"
          readOnly: true
      env:
        - name: KEYNAME
          value: $(params.secretKeyName)
        - name: NOTIFY_SUCCESS
          value: $(params.notifySuccess)
      script: |
        #!/usr/bin/env bash
        set -eux

        if [ -z "${KEYNAME}" ] ; then
          echo "No secret key name provided via the 'secretKeyName' pipeline parameter" \
            "provided in the release-plan"
          echo "No message will be sent to Slack"
          exit
        fi

        if [ -f "/etc/secrets/${KEYNAME}" ]; then
          echo "Setting WEBHOOK_URL from secret"
          set +x
          WEBHOOK_URL=$(cat "/etc/secrets/${KEYNAME}")
          set -x
        else
          echo "Error: Secret not defined properly. The key to use (${KEYNAME}) is defined in the 'secretKeyName'" \
            "pipeline parameter provided in the release-plan but the Secret does not contain the key"
          exit 1
        fi

        # check for release status and check if a managed pipeline failed
        IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
        RELEASECONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
          -o jsonpath='{.status.conditions}' | jq '.[] | select(.type == "ManagedPipelineProcessed")')

        RELEASESTATUS=$(jq -r '.reason' <<< "$RELEASECONDITIONS")

        if [[ "$RELEASESTATUS" == *"Failed"* ]]; then
          CONDITION_MESSAGE=$(jq -r '.message' <<< "$RELEASECONDITIONS" | awk NF)

          if [ -n "$CONDITION_MESSAGE" ]; then
            MESSAGE=$(printf "Release: %s/%s\n\nManaged pipelines failed: \`\`\`%s\`\`\`" \
              "$RELEASE_NAMESPACE" "$RELEASE_NAME" "$CONDITION_MESSAGE")
          else
            MESSAGE=$(printf "Release: %s/%s\n\nManaged pipelines failed." \
              "$RELEASE_NAMESPACE" "$RELEASE_NAME")
          fi
        elif [[ "${NOTIFY_SUCCESS}" == "true" ]] && [[ "$RELEASESTATUS" == *"Succeeded"* ]]; then
          CONDITION_MESSAGE=$(jq -r '.message' <<< "$RELEASECONDITIONS" | awk NF)

          if [ -n "$CONDITION_MESSAGE" ]; then
            MESSAGE=$(printf "Release: %s/%s\n\nManaged pipelines succeeded: \`\`\`%s\`\`\`" \
              "$RELEASE_NAMESPACE" "$RELEASE_NAME" "$CONDITION_MESSAGE")
          else
            MESSAGE=$(printf "Release: %s/%s\n\nManaged pipelines succeeded." \
              "$RELEASE_NAMESPACE" "$RELEASE_NAME")
          fi
        else
          echo "All pipelines succeeded. Not sending notification (notifySuccess=${NOTIFY_SUCCESS})."
          exit
        fi

        cat > /tmp/payload.json << EOF
        {"text": $(echo -n "$MESSAGE" | jq -Rsa .)}
        EOF
        # line above needs to be missing indentation

        echo "Calling Slack API with curl...."
        set +x
        curl -H "Content-type: application/json" --data-binary "@/tmp/payload.json"  \
          "${WEBHOOK_URL}"
        set -x
