---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: update-internal-services-resources
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: "release, tenant"
spec:
  description: |-
    Tekton pipeline to copy the internal-services resource files and update the manager yamls
    to the latest image in the github.com/redhat-appstudio/infra-common-deployments repository.
  params:
    - name: release
      type: string
      description:
        The namespaced name (namespace/name) of the Release custom resource initiating this pipeline execution
    - name: repoUrl
      type: string
      description: The repository where the internal-services manager files to update are
    - name: githubSecret
      type: string
      description: The secret containing a TOKEN key to authenticate with GitHub to the repoUrl
  tasks:
    - name: get-git-sha-image-ref-from-release
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/community-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/get-git-sha-image-ref-from-release/get-git-sha-image-ref-from-release.yaml
      params:
        - name: release
          value: $(params.release)
    - name: create-staging-pr
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/community-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/update-internal-services/update-internal-services.yaml
      params:
        - name: deployment
          value: staging
        - name: repoUrl
          value: $(params.repoUrl)
        - name: githubSecret
          value: $(params.githubSecret)
        - name: image
          value: $(tasks.get-git-sha-image-ref-from-release.results.imageRef)
    - name: create-production-pr
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: https://github.com/konflux-ci/community-catalog.git
          - name: revision
            value: development
          - name: pathInRepo
            value: tasks/update-internal-services/update-internal-services.yaml
      params:
        - name: deployment
          value: production
        - name: repoUrl
          value: $(params.repoUrl)
        - name: githubSecret
          value: $(params.githubSecret)
        - name: image
          value: $(tasks.get-git-sha-image-ref-from-release.results.imageRef)
