---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: sample-pipeline
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: release
spec:
  description: |-
    Sample pipeline that demonstrates how to use the sample-task to retrieve and print Release and ReleasePlan CRs.

    ⚠️ Note: This is a sample pipeline that should be kept simple to serve as a good example
    of how to construct a tenant task, so any non-bugfix contributions should be moved
    to a new or existing duplicate of this pipeline.
  params:
    - name: release
      type: string
      description: Namespaced name of release - should be in format "namespace/name"
    - name: releasePlan
      type: string
      description: Namespaced name of release plan - should be in format "namespace/name"
    - name: taskGitUrl
      type: string
      description: The url to the git repo where the community-catalog tasks to be used are stored
      default: https://github.com/konflux-ci/community-catalog.git
    - name: taskGitRevision
      type: string
      description: The revision in the taskGitUrl repo to be used
  tasks:
    - name: sample-task
      taskRef:
        resolver: "git"
        params:
          - name: url
            value: $(params.taskGitUrl)
          - name: revision
            value: $(params.taskGitRevision)
          - name: pathInRepo
            value: tasks/sample-task/sample-task.yaml
      params:
        - name: release
          value: $(params.release)
        - name: releasePlan
          value: $(params.releasePlan)